# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='number',
            name='name',
        ),
        migrations.AddField(
            model_name='number',
            name='number_Of_Graph',
            field=models.CharField(default=1, max_length=3),
        ),
    ]
