# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20160330_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='number_Of_Graph',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
