# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_clients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='graphs',
        ),
        migrations.AddField(
            model_name='clients',
            name='password',
            field=models.CharField(default='1234', max_length=20),
        ),
    ]
