# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 11:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_user_graphs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='graphs',
            new_name='graphs_id',
        ),
    ]
