# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20160331_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='graphs_id',
        ),
    ]
