# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 11:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0022_remove_user_graphs_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Graph',
        ),
        migrations.AddField(
            model_name='clients',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
